# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c258dbba4b6421f5e6b8c907f9b269c1c460603b26d2cec59854fab3fef460f524553b583d68302d9e274d3e31eb8f675aa7af49830c648b8c6727286794b80

test:
  secret_key_base: f0cfd32ca05637c6dbc1ae1ba464471c03a982cb1e72fd8e3c9569058e15c38020889b449d2bfe04277b4cd5b0e822674a7467c8c869c994dae09f2d1f787eaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
